import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/contexts/ToastContext";
import { AppBootstrap } from "@/components/AppBootstrap";

export const metadata: Metadata = {
  title: "RemoScreen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ToastProvider>{children}</ToastProvider>
        <AppBootstrap />
      </body>
    </html>
  );
}
